class MercadoLibreConstants:
    API_HOST = "https://api.mercadolibre.com"
    TOKEN_URL = "/oauth/token"
    TEST_USER_URL = "/users/test_user"
    TG_CODE = "tg_code"
    REDIRECT_URL = "redirect_url"
    SITE = "site_id"
    APP_ID = "app_id"
    APP_SECRET = "app_secret"
    APP_TOKEN = "app_token"
