openapi: 3.0.0
info:
  description: API to access the MercadoLibre service in the Sysmika SDK. Provides a gateway to operations on the MercadoLibre platform
  version: "0.1"
  title: MercadoLibre API
  contact:
    email: gaston.doval@globant.com
tags:
  - name: admins
    description: QA/Production secured calls
  - name: developers
    description: Endpoints used for development and testing

servers:
  - url: 127.0.1:5000
    description: For local development using Flask

paths:
  /user/test:
    get:
      tags:
        - developers
      summary: Creates a test user on a MercadoLibre account
      operationId: create_test_user
      description: |
        By passing the TG-Code for a specific MercadoLibre app, the endpoint will generate an access token
        and then create a test user. This user can be used to test the basic actions on the MercadoLibre platform
      responses:
        '200':
          description: User created
          content:
            application/json:
              schema:
                type: TestUser
                $ref: "../specs/schemas/test-user.json"
        400:
          description: Invalid grant
          content:
            application/json:
              schema:
                type: string
      parameters:
        - in: header
          name: access_token
          description: Token to authenticate operations on the MercadoLibre platform.
          required: true
          example: "{access_token: AG-90128301}"
          content:
            application/json:
              schema:
                type: "string"
          type: string
        - in: header
          type: string
          name: site_id
          example: "{site_id: MLA}"
          content:
            application/json:
              schema:
                type: "string"
          description: Id of the MercadoLibre site (Country)

  /auth/access_token:
    get:
      tags:
        - developers
        - admins
      summary: Generates an access token on the MercadoLibre site.
      operationId: generate_access_token
      responses:
        '200':
          description: An AccessToken object is generated.
          content:
            application/json:
              schema:
                type: AccessToken
                $ref: "../specs/schemas/access-token.json"
        default:
          description: "Access token creation failed"
          content:
            application/json:
              schema:
                type: string
      parameters:
        - in: header
          name: tg_code
          type: string
          required: true
          example: "{tg_code: TG-123456}"
          content:
            application/json:
              scchema:
                type: "string"
          $ref:
          descriprion: "Code generated by the MercadoLibre app on user authentication"
        - in: header
          name: redirect_url
          required: true
          example: "{redirect_url: http://sysmika.com.ar}"
          content:
            application/json:
              schema:
                type: "string"
          description: "Redirect URL specified on the user app on MercadoLibre"

  /auth/refresh_token:
    get:
      tags:
        - developer
        - admins
      summary: Refresh the access token, before expiration (after 6 hours of being generated)
      operationId: refresh_access_token
      responses:
        '200':
          description: An AccessToken object is generated.
          content:
            application/json:
              schema:
                type: AccessToken
                $ref: "../specs/schemas/access-token.json"
        default:
          description: Failed request
          content:
            application/json:
              schema:
                type: string
      parameters:
        - in: header
          name: refreh_token
          required: true
          example: "{refresh_token: TG-1234}"
          content:
            application/json:
              schema:
                type: string
          description: Code needed to fresh the access token. It generates automaically when requesting an access token

